spring.application.name=notification-service

server.port=8083

### MAIL PROPERTIES / MAIL TRAP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=96a0cdf519a933
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

### KAFKA CONSUMER PROPERTIES
# Kafka broker address (where your Kafka cluster is running)
spring.kafka.bootstrap-servers=localhost:9092
# Consumer group ID to coordinate reading from Kafka topics
spring.kafka.consumer.group-id=notification-service
# Deserializer for message keys (convert bytes to String)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Deserializer for message values (convert JSON to Java objects)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Mapping between topic names and Java classes for JSON deserialization
spring.kafka.consumer.properties.spring.json.type.mapping=event:com.pgs.microservices.order.event.OrderPlacedEvent
