spring.application.name=notification-service

server.port=8083

### MAIL PROPERTIES / MAIL TRAP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=96a0cdf519a933
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

### KAFKA CONSUMER PROPERTIES
# Kafka broker address to connect the consumer/producer
spring.kafka.bootstrap-servers=localhost:9092
# Consumer group ID for coordinating message consumption
spring.kafka.consumer.group-id=notification-service
# Converts message keys from bytes to String
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Deserializes message values from Avro format
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
# URL of Confluent Schema Registry to fetch Avro schemas
spring.kafka.consumer.properties.schema.registry.url=http://127.0.0.1:8085
# Use generated SpecificRecord classes instead of GenericRecord
spring.kafka.consumer.properties.specific.avro.reader=true

# Loki URL
loki.url=http://localhost:3100/loki/api/v1/push
