version: '4'  # Docker Compose file format version

services:
  mysql:
    image: mysql:8.3.0  # Use the official mysql image (v 8.3.0)
    container_name: mysql  # Set a custom name for the container
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # Set the root username
    ports:
      # Mapping local port (left) to container's port (right)
      - "3307:3306"  # Expose Mysql port to the host
    volumes:
      - ./mysql:/var/lib/mysql  # Mount the local './mysql' directory 
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount SQL script to initialize DB at container startup
