spring.application.name=order-service
server.port=8081

### DB Config
spring.datasource.url=jdbc:mysql://localhost:3307/order_service
spring.datasource.username=root
spring.datasource.password=mysql
# Disabled since we use flyway DB migration
spring.jpa.hibernate.ddl-auto=none
inventory.url=http://localhost:8082

## OPEN API
springdoc.swagger-ui.path=/swagger-ui.html
# JSON OPEN API http://localhost:8081/api-docs
springdoc.api-docs.path=/api-docs