spring.application.name=product-service
spring.data.mongodb.uri=mongodb://root:password@localhost:27018/product-service?authSource=admin

##OPEN API
springdoc.swagger-ui.path=/swagger-ui.html
# JSON OPEN API http://localhost:8080/api-docs
springdoc.api-docs.path=/api-docs